apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ .Values.labels.key}}: {{ .Values.labels.value }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{ .Values.labels.key}}: {{ .Values.labels.value }}
  template:
    metadata:
      labels:
        {{ .Values.labels.key}}: {{ .Values.labels.value }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 80