apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    {{ .Values.labels.key}}: {{ .Values.labels.value }}
  ports:
  - name: {{ .Values.container.name }}
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.nodeport }}
  type: NodePort