apiVersion: v1
name: harbor
version: 1.3.2
appVersion: 1.10.2
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
- harbor
home: https://github.com/JackieYou/demo-charts/tree/master/harbor
icon: https://markdown-1300017440.cos.ap-shanghai.myqcloud.com/mweb/harbor.png
sources:
- https://github.com/JackieYou/demo-charts/tree/master/harbor
- https://github.com/goharbor/harbor-helm
- https://github.com/goharbor/harbor
maintainers:
- name: Jiqing You
  email: jiqing@rancher.com
